"""fix demo_model.col_decimal

Revision ID: 479a8fdce8be
Revises: 7cbf4de6858d
Create Date: 2025-04-03 00:49:14.897939

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '479a8fdce8be'
down_revision: Union[str, None] = '7cbf4de6858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demo_model', 'col_decimal',
               existing_type=sa.REAL(),
               type_=sa.DECIMAL(precision=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demo_model', 'col_decimal',
               existing_type=sa.DECIMAL(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
