"""fix decimal precision

Revision ID: 6cb993f5758e
Revises: 479a8fdce8be
Create Date: 2025-04-05 00:31:48.871338

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cb993f5758e'
down_revision: Union[str, None] = '479a8fdce8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demo_model', 'col_decimal',
               existing_type=sa.NUMERIC(precision=8),
               type_=sa.DECIMAL(precision=16, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demo_model', 'col_decimal',
               existing_type=sa.DECIMAL(precision=16, scale=4),
               type_=sa.NUMERIC(precision=8),
               existing_nullable=False)
    # ### end Alembic commands ###
